### ISSUE TITLE
NaN values produced by tomographic kernel

### ISSUE THREAD

**Issue by rcyndie** [Joshuaalbert/bayes_gain_screens#43] opened 2022-04-22 13:32 UTC
I have tried using this repository to produce the Cholesky matrix corresponding to the tomographic kernel. I am currently working from the master branch in a 3.7.10 Python environment.

1. I have run the [tomographic_kernel script](https://github.com/Joshuaalbert/bayes_gain_screens/blob/master/bayes_gain_screens/tomographic_kernel/tomographic_kernel.py) script but I encountered an error relevant to the geodesic's jax array definition and attribute (not sure how to fix it?)

2. I also tried running the [simulate_ionosphere_phase_screen script](https://github.com/Joshuaalbert/bayes_gain_screens/blob/master/bin/simulate_ionosphere_phase_screen.py) and I ran the debug_main() with the default settings available. However, the Cholesky matrix produced was full of NaN values. I traced these NaN values to their first occurrence in the mean and covariance on lines 225 and 228 in this script. This led me back to debugging the tomographic kernel object in 1.

3. I have also tried building the singularity image from the given description and encountered the same error in 2.

Can you please advise on how to fix the issue?
I also had to install some missing dependencies such as astropy, tables, jaxlib and h5parm.

![nans_meanandcov](https://user-images.githubusercontent.com/30832777/164724180-28ad4ab6-c2e3-4abe-a4b3-168a768d94f2.png)
![jaxarray_errorwithattribute](https://user-images.githubusercontent.com/30832777/164724191-92fdf2ff-9046-42b8-b273-e35a6e40f765.png)

**Comment by Joshuaalbert** [comment] 2022-04-24 10:39
@rcyndie happy to help.

I rechecked https://github.com/Joshuaalbert/bayes_gain_screens/blob/master/bin/simulate_ionosphere_phase_screen.py and it works. Try starting from there. 

1. The GeodesicTuple is a required structure to hold the coordinates going in. Looks like you tried to use a DeviceArray.
2. Nans are a result of the numerical approximation to the kernel. Make sure 64 bit is enabled, see the top of [here](https://github.com/Joshuaalbert/bayes_gain_screens/blob/master/bin/simulate_ionosphere_phase_screen.py) for how to set 64 bit. In addition try making `S_marg` larger. This will better approximate the double integral required to compute the tomographic kernel. The sum of many pos-def functions is again pos-def, but sometimes small numerical errors violate this. These errors build up due to catastrophic cancellation.
3. I haven't updated the singularity recently, I could stick to conda + `pip install -r requirements.txt` method.

I'm available to help, so let me know if this information is enough to get you going.

**Comment by Joshuaalbert** [comment] 2022-04-25 08:53
The covariance matrix shouldn't have nan's, so I'd like to see the code you're using. Could you share it in a gist?
If the matrix square root is getting nan's that's a different story, and we can tackle that separately.

![Screenshot from 2022-04-25 10-50-56](https://user-images.githubusercontent.com/14807032/165054936-1a404e39-6f34-4f55-aa0c-9ebedc427090.png)

**Comment by Joshuaalbert** [comment] 2022-04-25 12:59
Here is some further help regarding using the cholesky. If you do not explicitly require the lower-triangular matrix square root, then there are other robust methods to computing the matrix square root.

The way that I do this in the simulation is to first try a cholesky, and then if it fails then use SVD:

```python
def msqrt(A):
    """
    Computes the matrix square-root using SVD, which is robust to poorly conditioned covariance matrices.
    Computes, L such that L @ L.H = A

    Args:
    A: [N,N] Square matrix to take square root of.

    Returns: maximum eigen value, minimum eigen value, matrix square root [N,N] matrix.
    """
    U, s, Vh = jnp.linalg.svd(A)
    max_eig = jnp.max(s)
    min_eig = jnp.min(s)
    L = U * jnp.sqrt(s)
    return max_eig, min_eig, L
```

**Comment by Joshuaalbert** [comment] 2022-04-25 14:01
More information on your use. The condition number of the covariance can be very large (poorly conditioned). This means the largest eigen value is really large, and the smallest eigenvalue is really small.

When the condition number is very large, numerical instabilities will result when doing matrix inverse, determinants, etc.
In these cases, small changes in inversions lead to large difference in results (blowing up errors), so increasing `S_marg` can be good. Note, however when you increase `S_marg` this also changes the condition number because the covariance changes. See here, doubling `S_marg` increases condition number by a factor of 10.

```python
#S_marg=25 ->  Condition: 3.1487642504726068e+16, minimum/maximum eigen values 4.584112084868654e-11, 1443428.8252993866
 #S_marg=50 -> Condition: 5.6699479485156486e+17, minimum/maximum eigen values 2.0612237813161506e-12, 1168703.1550305176
```

**Comment by JSKenyon** [comment] 2022-04-26 13:07
@Joshuaalbert I also encountered NaN values when attempting to run `https://github.com/Joshuaalbert/bayes_gain_screens/blob/master/bin/simulate_ionosphere_phase_screen.py` with no arguments. I believe this is supposed to run with a preconfigured set of arguments? Regardless, I can confirm that I also see NaN values.

Did you run in a fresh virtual environment @Joshuaalbert? I ask because the package isn't really in an installable state at present - perhaps you could provide a pip freeze or conda equivalent? Unfortuantely this isn't something I can readily debug on my end as I really am just running `simulate_ionosphere_phase_screen.py` as is.

cc'ing @o-smirnov

Edit: Bear with me - I see that some changes have been made since I last attempted this. Rerunning now - will post my results.

**Comment by Joshuaalbert** [comment] 2022-04-26 13:52
Okay, pull and try again. I've tested with a few different settings and it works. I pushed some changes to make sure that 64 bit is loaded, and other small changes.

This install use

```bash
git clone https://github.com/Joshuaalbert/bayes_gain_screens.git
cd bayes_gain_screens
pip install -r requirements.txt
pip install --no-deps pyregion pyparsing
pip install .
```

Always prefer the `pip install .` instead of `python setup.py install` as pip plays well with most things.

**Comment by JSKenyon** [comment] 2022-04-26 13:56
> Okay, pull and try again. I've tested with a few different settings and it works. I pushed some changes to make sure that 64 bit is loaded, and other small changes.
> 
> This install use
> 
> ```shell
> git clone https://github.com/Joshuaalbert/bayes_gain_screens.git
> cd bayes_gain_screens
> pip install -r requirements.txt
> pip install --no-deps pyregion pyparsing
> pip install .
> ```
> 
> Always prefer the `pip install .` instead of `python setup.py install` as pip plays well with most things.

Awesome - will give it a go.

**Comment by JSKenyon** [comment] 2022-04-26 14:21
Thanks @Joshuaalbert, this now seems to be working after the changes you made in the last couple of days.

I have taken the liberty of opening a PR to make setup a little cleaner - hope that is helpful.

**Comment by Joshuaalbert** [comment] 2022-04-26 14:28
Great, shall I close this issue then?

**Comment by JSKenyon** [comment] 2022-04-26 14:28
Sure - I am sure @rcyndie can comment if she runs into further trouble and it needs to be reopened. Thanks for your speedy responses!

**Comment by Joshuaalbert** [comment] 2022-04-26 14:39
No problem, happy to help

**Closed as completed by Joshuaalbert** 2022-04-26 14:39 UTC
